### ISSUE TITLE
翻译错误

### ISSUE THREAD

**Issue by 1366596157** [LuoManGit/effctiveJava3#2]
原文：Java 8 requires all static members of an interface to be public. 

翻译：由于Java8 中要求所有的静态成员必须是私有的

第一章的内容，应该是公有的

**Comment by LuoManGit** [comment]
多谢指出~ 已经修改啦~

**Comment by 1366596157** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我已收到您的邮件。谢谢！
